/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author luis
 */
public class Aprendisaje extends javax.swing.JFrame {

    /**
     * Creates new form Aprendisaje
     */
    public Aprendisaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ejecutar Aprendisaje");

        jPanel1.setBackground(new java.awt.Color(201, 205, 209));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 30, 30));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 30, 30));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 30, 30));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 30, 30));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 30));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 30, 30));

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, 30));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 30, 30));

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 30, 30));

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, 30));

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 30, 30));

        jButton18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 30, 30));

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 30, 30));

        jButton20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 30, 30));

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 30, 30));

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 30, 30));

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 30, 30));

        jButton24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 30, 30));

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 30, 30));

        jButton26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 30, 30));

        jButton27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 30));

        jButton28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 30, 30));

        jButton29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 30, 30));

        jButton30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 30, 30));

        jButton31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 30, 30));

        jButton32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 30, 30));

        jButton33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jButton34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        jButton35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 30, 30));

        jButton36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 30, 30));

        jButton37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 30, 30));

        jButton38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 30, 30));

        jButton39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 30));

        jButton40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jButton41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        jButton42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 30, 30));

        jButton43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 30, 30));

        jButton44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 30, 30));

        jButton45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 30, 30));

        jButton46.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 30));

        jButton47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 30, 30));

        jButton48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 30, 30));

        jButton49.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 30, 30));

        jButton50.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 30, 30));

        jButton51.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 30, 30));

        jButton52.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 30, 30));

        jButton53.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 30, 30));

        jButton54.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 30, 30));

        jButton55.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 30, 30));

        jButton56.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 30, 30));

        jButton57.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 30, 30));

        jButton58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 30, 30));

        jButton59.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 30, 30));

        jButton60.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 30, 30));

        jButton61.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 30, 30));

        jButton62.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 30, 30));

        jButton63.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 30, 30));

        jButton64.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 30, 30));

        jButton65.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 30, 30));

        jButton66.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 30, 30));

        jButton67.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 30, 30));

        jButton68.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 30, 30));

        jButton69.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 30, 30));

        jButton70.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 30, 30));

        jButton71.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 30, 30));

        jButton72.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 30, 30));

        jButton73.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 30, 30));

        jButton74.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 30, 30));

        jButton75.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 30, 30));

        jButton76.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 30, 30));

        jButton77.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 30, 30));

        jButton78.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 30, 30));

        jButton79.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 30, 30));

        jButton80.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 30, 30));

        jButton81.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 30, 30));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 100, -1));

        jButton3.setText("Digitalizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 100, -1));

        jLabel5.setText("Resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aprendisaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aprendisaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aprendisaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aprendisaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aprendisaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
