/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesAdicionales.AdminArchivos;
import ClasesAdicionales.Globals;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import test.testInicializar;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import perceptronmultisalida.Entrenamiento;
import perceptronmultisalida.Funcion;
import perceptronmultisalida.Inicializar;
import perceptronmultisalida.Perceptron;
import perceptronmultisalida.Resultado;
import perceptronmultisalida.TablaEntrenamiento;

/**
 *
 * @author Mariela Rodriguez
 */
public class Letras extends javax.swing.JFrame {
    private int        nLineas=0;
    private int        contadorS=0;
    private int        contadorL=0;
    private int        nEntradas;
    private int        nSalidas;
    private int        alfa;
    private int        teta;
    private String     nameFile;
    private List<JButton> b = new ArrayList<>();
    private boolean    noLetras = false;
    
    public Letras() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEntradas = new javax.swing.JTextField();
        txtnameFile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        txtAlfa = new javax.swing.JTextField();
        txtTeta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSalidas = new javax.swing.JTextField();
        btnEntrenar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        btnArchivo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        btnReconocer = new javax.swing.JButton();
        txtPalabraCorrecta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnPronunciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cantidad de Entradas:");

        jLabel2.setText("Cantidad de Salidas:");

        jLabel3.setText("Nombre Tabla de Entrenamiento:");

        txtEntradas.setName(""); // NOI18N
        txtEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Entrenamiento Perceptron MultiSalida - Reconocimiento de palabras");

        btnCrear.setText("Crear Perceptron");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        txtAlfa.setName(""); // NOI18N
        txtAlfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlfaActionPerformed(evt);
            }
        });

        txtTeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTetaActionPerformed(evt);
            }
        });

        jLabel6.setText("Taza de aprendisaje:");

        jLabel7.setText("Umbral:");

        txtSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidassActionPerformed(evt);
            }
        });

        btnEntrenar.setText("Ejecutar Entrenamiento");
        btnEntrenar.setEnabled(false);
        btnEntrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrenarActionPerformed(evt);
            }
        });

        jLabel5.setText("Seleccione el archivo que contiene las palabras:");

        txtArchivo.setEnabled(false);

        btnArchivo.setText("Abrir Archivo");
        btnArchivo.setAutoscrolls(true);
        btnArchivo.setEnabled(false);
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingrese una palabra: ");

        txtPalabra.setEnabled(false);

        btnReconocer.setText("Reconocer");
        btnReconocer.setAutoscrolls(true);
        btnReconocer.setEnabled(false);
        btnReconocer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconocerActionPerformed(evt);
            }
        });

        txtPalabraCorrecta.setEnabled(false);

        jLabel9.setText("Palabra Correcta:");

        btnPronunciar.setText("Pronunciar");
        btnPronunciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPronunciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEntrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnArchivo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAlfa, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(txtTeta)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnameFile)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCrear))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtPalabra)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnReconocer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtPalabraCorrecta)))
                                    .addComponent(btnPronunciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtnameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArchivo)))
                .addGap(18, 18, 18)
                .addComponent(btnEntrenar)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReconocer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPalabraCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(btnPronunciar)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        this.nEntradas = Integer.parseInt(txtEntradas.getText());
        this.nSalidas = Integer.parseInt(txtSalidas.getText());
        this.alfa = Integer.parseInt(txtAlfa.getText());
        this.teta = Integer.parseInt(txtTeta.getText());
        this.nameFile = txtnameFile.getText();
        contadorL=0;
        AdminArchivos.escribir(nameFile,"");
        
        btnCrear.setEnabled(false);
        txtEntradas.setEnabled(false);
        txtSalidas.setEnabled(false);
        txtAlfa.setEnabled(false);
        txtTeta.setEnabled(false);
        txtnameFile.setEnabled(false);
        txtArchivo.setEnabled(true);
        btnArchivo.setEnabled(true);
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradasActionPerformed

    private void txtAlfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlfaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlfaActionPerformed

    private void txtTetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTetaActionPerformed

    private void txtSalidassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidassActionPerformed

    private void btnEntrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrenarActionPerformed
        
        
        //<====={Preparar archivo de entrenamiento}=====>
        
        int maxlenght = 24;
        char [] Arreglo = new char[32];
        Arreglo[0] = 'a';
        Arreglo[1] = 'b';
        Arreglo[2] = 'c';
        Arreglo[3] = 'd';
        Arreglo[4] = 'e';
        Arreglo[5] = 'f';
        Arreglo[6] = 'g';
        Arreglo[7] = 'h';
        Arreglo[8] = 'i';
        Arreglo[9] = 'j';
        Arreglo[10] = 'k';
        Arreglo[11] = 'l';
        Arreglo[12] = 'm';
        Arreglo[13] = 'n';
        Arreglo[14] = 'ñ';
        Arreglo[15] = 'o';
        Arreglo[16] = 'p';
        Arreglo[17] = 'q';
        Arreglo[18] = 'r';
        Arreglo[19] = 's';
        Arreglo[20] = 't';
        Arreglo[21] = 'u';
        Arreglo[22] = 'v';
        Arreglo[23] = 'w';
        Arreglo[24] = 'x';
        Arreglo[25] = 'y';
        Arreglo[26] = 'z';
        Arreglo[27] = 'á';
        Arreglo[28] = 'é';
        Arreglo[29] = 'í';
        Arreglo[30] = 'ó';
        Arreglo[31] = 'ú';
        //System.out.println(this.txtArchivo.getText());
        try {
            
            Globals.palabras = Funcion.leer_Archivo_Arreglo(this.txtArchivo.getText(), this.nSalidas);
            
            /*
            for (int i = 0; i < this.nSalidas; i++) {
                System.out.println(Globals.palabras[i]);
            }
            */
            String datos = "";
            int q = 1;
            for (String palabra: Globals.palabras) {
                //AdminArchivos.agregarDatos(nameFile, (Funcion.cadenaEntradas(palabra, Arreglo, maxlenght) + Funcion.cadenaSalidas(palabras, palabra)) );
                //AdminArchivos.agregarDatos(nameFile, (Funcion.mapaDatos(palabras, palabra, Arreglo, maxlenght)) );
                //System.out.println(Funcion.mapaDatos(palabras, palabra, Arreglo, maxlenght));
                datos += Funcion.mapaDatos(Globals.palabras, palabra, Arreglo, maxlenght) + "\n";
                q++;
                if (q == 2){
                    maxlenght-=1;
                }
            }
            AdminArchivos.agregarDatos(nameFile, datos.substring(0, datos.length() - 1));
            System.out.println("Los datos han sido guardados");
            
            // Funcion: Leer archivo csv y guardar las palabras en el arreglo palabras
        } catch (IOException ex) {
            Logger.getLogger(Letras.class.getName()).log(Level.SEVERE, null, ex);
            
            System.out.println("Ha ocurrido un error");
            
        }
        
        
        
        
        
        
        
        // TODO add your handling code here:
        // <=== {Inicializar} ===>
        ArrayList<ArrayList<Integer>> vectorEntrada = new ArrayList<>();
        ArrayList<ArrayList<Integer>> vectorSalida = new ArrayList<>();

        nLineas = Inicializar.leerFilasCsv(
            nameFile,
            vectorEntrada,
            vectorSalida,
            nEntradas,
            nSalidas
        );
        if (nLineas == -1){
            JOptionPane.showMessageDialog(this, "Error al leer el documento, los datos no coinciden con las entras y salidas especificadas", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }

        // Instancia Tabla_Verdad
        Globals.tabla_verdad = new TablaEntrenamiento(
            nEntradas,
            nSalidas,
            nLineas,
            new int[nLineas][nEntradas],
            new int[nLineas][nSalidas],
            new int[nLineas][nSalidas]
        );

        // Instancia Perceptron
        Globals.perceptron = new Perceptron(
            alfa,
            teta,
            new int[nLineas][nEntradas][nSalidas],
            new int[nLineas][nSalidas],
            new int[nLineas][nEntradas][nSalidas],
            new int[nLineas][nSalidas],
            new int[nLineas][nSalidas],
            new int[nLineas][nSalidas]
        );

        Inicializar.InicializarTablaEntrenamiento(Globals.tabla_verdad, vectorEntrada, vectorSalida);
        Inicializar.InicializarPerceptron(Globals.perceptron, Globals.tabla_verdad);
        
        System.out.println("Las tablas han sido inicializadas");
        
        
        
        
        
        // <=== {Entrenar} ===>
        System.out.println("Ejecutando Entrenamiento");
        Entrenamiento.Entrenar(
            Globals.perceptron,
            Globals.tabla_verdad
        );
        System.out.println("Entrenamiento Finalizado");
        
        /*
        System.out.println("<===== {Informacion Basica del Perceptron} =====>");
        Resultado.MostrarPerceptronAtributos(Globals.perceptron, Globals.tabla_verdad);

        System.out.println("<===== {Informacion de las Entradas} =====>");
        Resultado.MostrarTablaEntradas(Globals.tabla_verdad);
        Resultado.MostrarTablaTarget(Globals.tabla_verdad);
        Resultado.MostrarTablaBias(Globals.tabla_verdad);
        System.out.println("");

        System.out.println("<===== {Informacion de los Pesos} =====>");
        Resultado.MostrarPerceptronWeight(Globals.perceptron, Globals.tabla_verdad);
        Resultado.MostrarPerceptronWeightChange(Globals.perceptron, Globals.tabla_verdad);

        System.out.println("<===== {Informacion de la Funcion de Activacion} =====>");
        Resultado.MostrarPerceptronFuncion(Globals.perceptron, Globals.tabla_verdad);

        System.out.println("");
        System.out.println("<===== {Ejecución del Perceptron} =====>");
        Funcion.Ejecutar(Globals.perceptron, Globals.tabla_verdad);

        /*

        */
        txtArchivo.setEnabled(false);
        btnArchivo.setEnabled(false);
        btnEntrenar.setEnabled(false);
        btnReconocer.setEnabled(true);
        txtPalabra.setEnabled(true);
        txtPalabraCorrecta.setEnabled(true);
        /*
        Aprendisaje form2 = new Aprendisaje();
        form2.setVisible(true);
        */
    }//GEN-LAST:event_btnEntrenarActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        JFileChooser fc= new JFileChooser(new File ("").getAbsolutePath ());
        
        int seleccion = fc.showOpenDialog(this);
        if (seleccion== JFileChooser.APPROVE_OPTION) {
                File fichero= fc.getSelectedFile();
            
                this.txtArchivo.setText(fichero.getName());              
                this.btnEntrenar.setEnabled(true);
        }else{
            System.out.println("Adios");
        }
        
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnReconocerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconocerActionPerformed
        this.txtPalabraCorrecta.setText(  Funcion.EjecutarAprendisaje(
                Globals.perceptron
                , Globals.tabla_verdad
                , Funcion.cadenaEntradas(this.txtPalabra.getText(), 23)
                , Globals.palabras
        )  );
    }//GEN-LAST:event_btnReconocerActionPerformed

    private void btnPronunciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPronunciarActionPerformed
        String frase = "";
        frase = this.txtPalabraCorrecta.getText();
        System.setProperty("mbrola.base", "C:\\Users\\Luis Fernando\\Desktop\\mbrola\\mbrola\\mbrola");
        VoiceManager manager =  VoiceManager.getInstance();
        Voice voz = manager.getVoice("mbrola_us1");// se puede usar voz mbrola_us1,mbrola_us2, mbrola_us3 kevin16
        voz.allocate();
            voz.speak(frase);
           /* for(int i=0; i<=10;i++){
            voz.speak(Integer.toString(i));
            }*/
            voz.deallocate();
        
        
    }//GEN-LAST:event_btnPronunciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Letras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Letras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Letras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Letras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Letras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEntrenar;
    private javax.swing.JButton btnPronunciar;
    private javax.swing.JButton btnReconocer;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAlfa;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtEntradas;
    private javax.swing.JTextField txtPalabra;
    private javax.swing.JTextField txtPalabraCorrecta;
    private javax.swing.JTextField txtSalidas;
    private javax.swing.JTextField txtTeta;
    private javax.swing.JTextField txtnameFile;
    // End of variables declaration//GEN-END:variables
}
