/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesAdicionales.AdminArchivos;
import java.awt.Color;

/**
 *
 * @author Mariela Rodriguez
 */
public class Principal extends javax.swing.JFrame {
    private static int nLineas=0;
    private static int contadorS=0;
    private static int contadorL=0;
    private int        nEntradas;
    private int        nSalidas;
    private String     nameFile;
    
    public int getnEntradas() {
        return nEntradas;
    }

    /**
     * @param nEntradas the nEntradas to set
     */
    public void setnEntradas(int nEntradas) {
        this.nEntradas = nEntradas;
    }

    /**
     * @return the nSalidas
     */
    public int getnSalidas() {
        return nSalidas;
    }

    /**
     * @param nSalidas the nSalidas to set
     */
    public void setnSalidas(int nSalidas) {
        this.nSalidas = nSalidas;
    }

    /**
     * @return the nameFile
     */
    public String getNameFile() {
        return nameFile;
    }

    /**
     * @param nameFile the nameFile to set
     */
    public void setNameFile(String nameFile) {
        this.nameFile = nameFile;
    }
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLinea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblNeurona = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn48 = new javax.swing.JButton();
        btn49 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn51 = new javax.swing.JButton();
        btn52 = new javax.swing.JButton();
        btn53 = new javax.swing.JButton();
        btn54 = new javax.swing.JButton();
        btn55 = new javax.swing.JButton();
        btn56 = new javax.swing.JButton();
        btn57 = new javax.swing.JButton();
        btn58 = new javax.swing.JButton();
        btn59 = new javax.swing.JButton();
        btn60 = new javax.swing.JButton();
        btn61 = new javax.swing.JButton();
        btn62 = new javax.swing.JButton();
        btn63 = new javax.swing.JButton();
        btnDigitalizar = new javax.swing.JButton();
        btnDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEntradas = new javax.swing.JTextField();
        txtSalida = new javax.swing.JTextField();
        txtnameFile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnEntrenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(201, 205, 209));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        txtLinea.setEnabled(false);
        jPanel1.add(txtLinea);
        txtLinea.setBounds(216, 63, 162, 20);

        jLabel5.setText("Lineas de Entrenamiento");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(12, 69, 118, 14);

        lblNeurona.setText("Entrenamiento Neurona");
        jPanel1.add(lblNeurona);
        lblNeurona.setBounds(12, 28, 114, 14);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setEnabled(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 100, -1));

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 30, 30));

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 30, 30));

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 30, 30));

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 30, 30));

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 30));

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 30, 30));

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, 30));

        btn10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 30, 30));

        btn11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 30, 30));

        btn12.setBackground(new java.awt.Color(255, 255, 255));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel2.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, 30));

        btn13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 30, 30));

        btn14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 30, 30));

        btn15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 30, 30));

        btn16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 30, 30));

        btn17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 30, 30));

        btn18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 30, 30));

        btn19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 30, 30));

        btn20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 30, 30));

        btn21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 30, 30));

        btn22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 30, 30));

        btn23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 30));

        btn24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 30, 30));

        btn25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 30, 30));

        btn26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 30, 30));

        btn27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 30, 30));

        btn28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 30, 30));

        btn29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 30, 30));

        btn30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 30, 30));

        btn31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 30, 30));

        btn32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 30, 30));

        btn33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 30, 30));

        btn34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 30, 30));

        btn35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 30, 30));

        btn36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 30, 30));

        btn37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 30, 30));

        btn38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 30, 30));

        btn39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 30, 30));

        btn40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn40, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 30, 30));

        btn41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 30, 30));

        btn42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn42, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 30, 30));

        btn43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 30, 30));

        btn44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 30, 30));

        btn45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 30, 30));

        btn46.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 30, 30));

        btn47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn47, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 30, 30));

        btn48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn48, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 30, 30));

        btn49.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn49, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 30, 30));

        btn50.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 30, 30));

        btn51.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 30, 30));

        btn52.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 30, 30));

        btn53.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn53, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 30, 30));

        btn54.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn54, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 30, 30));

        btn55.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn55, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 30, 30));

        btn56.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn56, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 30, 30));

        btn57.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 30, 30));

        btn58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 30, 30));

        btn59.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn59, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 30, 30));

        btn60.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 30, 30));

        btn61.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn61, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 30, 30));

        btn62.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn62, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 30, 30));

        btn63.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn63, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 30, 30));

        btnDigitalizar.setText("Digitalizar");
        btnDigitalizar.setEnabled(false);
        btnDigitalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitalizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnDigitalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(100, 110, 360, 270);

        btnDatos.setText("Digitalizar Datos");
        btnDatos.setEnabled(false);
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnDatos);
        btnDatos.setBounds(396, 63, 130, 23);

        jLabel1.setText("Cantidad de Entradas:");

        jLabel2.setText("Cantidad de Salidas:");

        jLabel3.setText("Nombre Tabla de Entrenamiento:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtEntradas.setName(""); // NOI18N
        txtEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradasActionPerformed(evt);
            }
        });

        txtSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Entrenamiento Perceptron MultiSalida - Letras");

        btnCrear.setText("Crear Perceptron");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEntrenar.setText("Ejecutar Entrenamiento");
        btnEntrenar.setEnabled(false);
        btnEntrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnCrear)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtnameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntrenar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        this.setnEntradas(Integer.parseInt(txtEntradas.getText()));
        this.setnSalidas(Integer.parseInt(txtSalida.getText()));
        this.setNameFile(txtnameFile.getText());
        
        AdminArchivos.escribir(getNameFile(),"");
        
        txtLinea.setEnabled(true);
        txtEntradas.setEnabled(false);
        txtSalida.setEnabled(false);
        txtnameFile.setEnabled(false);
        btnDatos.setEnabled(true);
        
        contadorS++;
        lblNeurona.setText("Entrenamiento Neurona " +contadorS);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaActionPerformed

    private void btnEntrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrenarActionPerformed

    private void btnDigitalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigitalizarActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        nLineas=(Integer.parseInt(txtLinea.getText()));
        contadorS++;
        btnDigitalizar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        btnDatos.setEnabled(false);
        txtLinea.setEnabled(false);
        
    }//GEN-LAST:event_btnDatosActionPerformed

    private void txtEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradasActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(btn1.getBackground() == Color.white){
            btn1.setBackground(Color.black);
        }else{
            btn1.setBackground(Color.white);
        }
        
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn46;
    private javax.swing.JButton btn47;
    private javax.swing.JButton btn48;
    private javax.swing.JButton btn49;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn51;
    private javax.swing.JButton btn52;
    private javax.swing.JButton btn53;
    private javax.swing.JButton btn54;
    private javax.swing.JButton btn55;
    private javax.swing.JButton btn56;
    private javax.swing.JButton btn57;
    private javax.swing.JButton btn58;
    private javax.swing.JButton btn59;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn60;
    private javax.swing.JButton btn61;
    private javax.swing.JButton btn62;
    private javax.swing.JButton btn63;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnDigitalizar;
    private javax.swing.JButton btnEntrenar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNeurona;
    private javax.swing.JTextField txtEntradas;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtSalida;
    private javax.swing.JTextField txtnameFile;
    // End of variables declaration//GEN-END:variables
}
